# -*- coding: utf-8 -*-
"""recommendation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhllT2qVIR3ZFYzTvnnCZnqd1hvETKyw
"""

# RECOMMENDATION MODEL
# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")  # Suppress warnings

# Step 2: Generate a realistic synthetic dataset

np.random.seed(42)
num_samples = 2000

data = {
    "user_id": np.arange(1, num_samples + 1),
    "commute_mode": np.random.choice(["car", "bus", "bike", "walk", "train", "EV"], num_samples, p=[0.35, 0.25, 0.1, 0.05, 0.15, 0.1]),
    "distance_km": np.random.uniform(1, 120, num_samples),
    "diet_type": np.random.choice(["veg", "non-veg", "mixed"], num_samples, p=[0.4, 0.3, 0.3]),
    "energy_usage_kWh": np.random.uniform(100, 700, num_samples),  # monthly usage
}

df = pd.DataFrame(data)

# Updated emission factors (kg CO₂ per km or per kWh)
emission_factors = {
    "car": 0.21, "bus": 0.089, "bike": 0.018, "walk": 0.0, "train": 0.041, "EV": 0.045
}
diet_factors = {"veg": 1.5, "non-veg": 4.2, "mixed": 2.7}

# Compute CO₂ emissions (realistic approximation)
df["commute_emission"] = df["distance_km"] * df["commute_mode"].map(emission_factors)
df["diet_emission"] = df["diet_type"].map(diet_factors)
df["energy_emission"] = (df["energy_usage_kWh"] / 30) * 0.4  # daily energy impact
df["total_emission"] = df["commute_emission"] + df["diet_emission"] + df["energy_emission"]

# Step 3: Encode categorical features

le_commute = LabelEncoder()
le_diet = LabelEncoder()
df["commute_mode_encoded"] = le_commute.fit_transform(df["commute_mode"])
df["diet_type_encoded"] = le_diet.fit_transform(df["diet_type"])

# Step 4: Train/test split

X = df[["commute_mode_encoded", "distance_km", "diet_type_encoded", "energy_usage_kWh"]]
y = df["total_emission"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train the model (optimized)

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    min_samples_split=4
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f"✅ Model trained successfully! MAE: {mean_absolute_error(y_test, y_pred):.2f} kg CO₂\n")

# Step 6: Manual User Input

print("🌍 Enter your daily lifestyle details:\n")

commute = input("Commute mode (car/bus/bike/walk/train): ").strip().lower()
distance = float(input("Average distance travelled per day (in km): "))
diet = input("Diet type (veg/non-veg/mixed): ").strip().lower()
energy = float(input("Average monthly energy usage (in kWh): "))

# Step 7: Predict CO₂ emission for user

commute_enc = le_commute.transform([commute])[0]
diet_enc = le_diet.transform([diet])[0]

features = np.array([[commute_enc, distance, diet_enc, energy]])
current_emission = model.predict(features)[0]
green_score = max(0, 100 - (current_emission / 0.7))  # Lower CO₂ → higher score
green_score = min(100, round(green_score, 2))

print(f"\n🌱 Estimated Daily CO₂ Emission: {current_emission:.2f} kg/day")
print(f"💚 Green Score: {green_score}/100")

# Step 8: Smart Recommendation Engine (Context-Aware)

def recommend_action(commute, distance, diet, energy):
    commute_enc = le_commute.transform([commute])[0]
    diet_enc = le_diet.transform([diet])[0]
    base_features = np.array([[commute_enc, distance, diet_enc, energy]])
    current_emission = model.predict(base_features)[0]

    alternatives = []
    for alt_commute in ["car", "bus", "bike", "walk", "train", "EV"]:
        for alt_diet in ["veg", "non-veg", "mixed"]:

            # 🧭 Realistic commute filtering
            if distance > 40 and alt_commute in ["walk", "bike"]:
                continue
            if distance > 90 and alt_commute in ["bus"]:
                continue
            if distance < 2 and alt_commute in ["car", "train", "bus"]:
                continue

            commute_enc_alt = le_commute.transform([alt_commute])[0]
            diet_enc_alt = le_diet.transform([alt_diet])[0]
            alt_features = np.array([[commute_enc_alt, distance, diet_enc_alt, energy]])
            alt_emission = model.predict(alt_features)[0]
            saving = current_emission - alt_emission

            if saving > 0:
                # 🌟 Assign comfort level dynamically
                if alt_commute in ["walk", "bike"] and distance > 30:
                    comfort = "★☆☆ (Low)"
                elif alt_commute in ["bus", "train"]:
                    comfort = "★★★ (Medium)"
                elif alt_commute == "EV":
                    comfort = "★★★★ (High)"
                else:
                    comfort = "★★★★★ (Very High)"

                # Weighted ranking: emission savings × comfort realism factor
                comfort_weight = {"★☆☆ (Low)": 0.7, "★★★ (Medium)": 0.9, "★★★★ (High)": 0.95, "★★★★★ (Very High)": 1.0}
                weighted_score = saving * comfort_weight[comfort]
                alternatives.append((alt_commute, alt_diet, round(saving, 2), comfort, weighted_score))

    # Sort by best weighted score
    alternatives = sorted(alternatives, key=lambda x: x[4], reverse=True)

    print("\n💡 Smart Recommendations for Lower CO₂ Footprint:")
    for rec in alternatives[:3]:
        print(f"➡ Switch to {rec[0]} and adopt a {rec[1]} diet → Save {rec[2]} kg/day | Comfort: {rec[3]}")

    if not alternatives:
        print("✅ You’re already following a low-carbon lifestyle!")

recommend_action(commute, distance, diet, energy)

# Step 9: Summary Feedback
if green_score >= 80:
    print("\n🏆 Excellent! You’re living an eco-friendly lifestyle.")
elif 50 <= green_score < 80:
    print("\n🌿 Good job! Some small tweaks can improve your footprint further.")
else:
    print("\n⚠️ High carbon footprint detected — try adopting some of the above suggestions.")

